FROM ghcr.io/tcarland/tcalibcore:v26.01.01
ARG RELEASE_VERSION=""

LABEL org.opencontainers.image.authors="Timothy C. Arland <tcarland at gmail.com" \
      org.opencontainers.image.base.name="ghcr.io/tcarland/tcalibcore:v26.01.01" \
      org.opencontainers.image.description="Trans-AM - Transcoding for Audio Media" \
      org.opencontainers.image.source="https://github.com/tcarland/transam" \
      org.opencontainers.image.title="transam" \
      org.opencontainers.image.version="${RELEASE_VERSION}"

USER root

ENV TCAMAKE_PROJECT=/opt
COPY . /opt/transam

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    flac \
    lame \
    libtag1-dev \
    libvorbis-dev \
    sox \
    vorbis-tools && \
    chown -R tdh:tdh /opt/transam

WORKDIR /opt/transam

RUN source resources/transam_release.env && \
    make && TCAMAKE_PREFIX="" make install && make clean

USER tdh

ENTRYPOINT [ "/usr/bin/tini", "--", "/opt/transam/bin/transam" ]
