name: C/C++ Build CI

on:
  push:
    tags: [ "v*" ]
    branches: [ "tca-23.08" ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Build Container
      run: docker build -t ${{ env.IMAGE_NAME }} -f Containerfile .

